---
version: '2'

networks:
  zookeeper:
    driver: bridge
  kafka:
    driver: bridge
  api:
    driver: bridge
  hadoop:
    external: true
  mail:
    driver: bridge

services:

  #---------------------------------------------------------------------------#
  # Zookeeper Cluster                                                         #
  #---------------------------------------------------------------------------#
  zookeeper-1:
    image: confluentinc/cp-zookeeper:3.1.1
    networks:
      - zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888

  #---------------------------------------------------------------------------#
  # Kafka Cluster                                                             #
  #---------------------------------------------------------------------------#
  kafka-1:
    image: confluentinc/cp-kafka:3.1.1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092

  kafka-2:
    image: confluentinc/cp-kafka:3.1.1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092

  kafka-3:
    image: confluentinc/cp-kafka:3.1.1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092

  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:3.1.1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry-1:8081

  #---------------------------------------------------------------------------#
  # REST proxy                                                                #
  #---------------------------------------------------------------------------#
  rest-proxy-1:
    image: confluentinc/cp-kafka-rest:3.1.1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_REST_LISTENERS: http://rest-proxy-1:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry-1:8081
      KAFKA_REST_HOST_NAME: rest-proxy-1


  #---------------------------------------------------------------------------#
  # RADAR Hot Storage                                                         #
  #---------------------------------------------------------------------------#
  mongo:
    image: mongo:3.2.10
    networks:
      - api
    ports:
      - "27017:27017"

  #---------------------------------------------------------------------------#
  # RADAR REST API                                                            #
  #---------------------------------------------------------------------------#
  tomcat:
    image: tomcat:8.0.37
    networks:
      - api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  #---------------------------------------------------------------------------#
  # RADAR Dashboard                                                           #
  #---------------------------------------------------------------------------#
  dashboard:
    image: radarcns/radar-dashboard:latest
    networks:
      - api
    ports:
      - "3000:3000"
    depends_on:
      - tomcat


  #---------------------------------------------------------------------------#
  # RADAR Cold Storage                                                        #
  #---------------------------------------------------------------------------#
  hdfs-datanode-1:
    image: uhopper/hadoop-datanode:2.7.2
    networks:
      - hadoop
    volumes:
      - "${HDFS_DATA_DIR_1}:/hadoop/dfs/data"
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hdfs-namenode:8020
      HDFS_CONF_dfs_replication: 2

  hdfs-datanode-2:
    image: uhopper/hadoop-datanode:2.7.2
    networks:
      - hadoop
    volumes:
      - "${HDFS_DATA_DIR_2}:/hadoop/dfs/data"
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hdfs-namenode:8020
      HDFS_CONF_dfs_replication: 2

  hdfs-namenode:
    build: hdfs-namenode
    image: radarcns/hdfs-namenode:2.7.2
    networks:
      - hadoop
    volumes:
      - "${HDFS_NAME_DIR_1}:/hadoop/dfs/name/1"
      - "${HDFS_NAME_DIR_2}:/hadoop/dfs/name/2"
    environment:
      CLUSTER_NAME: radar-cns
      HDFS_CONF_dfs_namenode_name_dir: file:///hadoop/dfs/name/1,file:///hadoop/dfs/name/2

  #---------------------------------------------------------------------------#
  # Email server                                                              #
  #---------------------------------------------------------------------------#
  smtp:
    image: namshi/smtp:latest
    networks:
      - mail
    volumes:
      - /var/spool/exim
    env_file:
      - smtp.env

  #---------------------------------------------------------------------------#
  # RADAR mongo connector                                                     #
  #---------------------------------------------------------------------------#
  radar-mongodb-connector:
    image: radarcns/radar-mongodb-connector:0.1
    restart: on-failure:3
    volumes:
      - ./sink-radar.properties:/etc/kafka-connect/sink.properties
    networks:
      - zookeeper
      - kafka
      - api
    depends_on:
      - mongo
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
      - rest-proxy-1
    environment:
      CONNECT_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092,PLAINTEXT://kafka-3:9092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: "default"
      CONNECT_CONFIG_STORAGE_TOPIC: "default.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "default.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "default.status"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_OFFSET_STORAGE_FILE_FILENAME: "/tmp/connect2.offset"
      CONNECT_REST_ADVERTISED_HOST_NAME: "radar-mongodb-connector"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181

  #---------------------------------------------------------------------------#
  # RADAR HDFS connector                                                     #
  #---------------------------------------------------------------------------#
  radar-hdfs-connector:
    image: radarcns/radar-hdfs-connector:0.1
    restart: on-failure:3
    volumes:
      - ./sink-hdfs.properties:/etc/kafka-connect/sink.properties
    networks:
      - zookeeper
      - kafka
      - api
      - hadoop
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
      - rest-proxy-1
      - hdfs-datanode-1
      - hdfs-datanode-2
      - hdfs-namenode
    environment:
      CONNECT_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092,PLAINTEXT://kafka-3:9092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: "default"
      CONNECT_CONFIG_STORAGE_TOPIC: "default.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "default.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "default.status"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_OFFSET_STORAGE_FILE_FILENAME: "/tmp/connect2.offset"
      CONNECT_REST_ADVERTISED_HOST_NAME: "radar-hdfs-connector"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181

  #---------------------------------------------------------------------------#
  # RADAR backend streams                                                     #
  #---------------------------------------------------------------------------#
  radar-backend-stream:
    image: radarcns/radar-backend-kafka:0.1
    command:
      - stream
    networks:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
    volumes:
      - ./radar.yml:/etc/radar.yml

  #---------------------------------------------------------------------------#
  # RADAR backend monitor                                                     #
  #---------------------------------------------------------------------------#
  radar-backend-monitor:
    image: radarcns/radar-backend-kafka:0.1
    command:
      - monitor
    networks:
      - zookeeper
      - kafka
      - mail
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
      - smtp
    volumes:
      - ./radar.yml:/etc/radar.yml
