version: '2.1'
services:
  managementportal-postgresql:
    image: postgres:9.6.2
    # volumes:
    #     - ~/volumes/jhipster/managementportal/postgresql/:/var/lib/postgresql/
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: managementportal
    ports:
      - 5432:5432


