# Continuous integration and conditional deployment to stage
name: Main 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  DOCKER_COMPOSE_VERSION: 1.21.1
  DOCKER_COMPOSE: $HOME/bin/docker-compose

jobs:
  continuous-integration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Before install
        run: |
          docker --version
          mkdir -p "$HOME/bin";
          export PATH="$HOME/bin:$PATH";
          curl -L https://github.com/docker/compose/releases/download/${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-`uname -s`-`uname -m` > ${{ env.DOCKER_COMPOSE }};
          chmod +x "${{ env.DOCKER_COMPOSE }}";
          sudo ${{ env.DOCKER_COMPOSE }} --version
      
      - name: Standard stack
        run: |
          cd dcompose-stack/radar-cp-stack
          sudo ${{ env.DOCKER_COMPOSE }} up -d --build && sleep 15 && [ -z "$(sudo ${{ env.DOCKER_COMPOSE }} ps | tail -n +3 | grep " Exit ")" ]
          sudo ${{ env.DOCKER_COMPOSE }} down
      
      - name: With email and HDFS support
        run: |
          cd dcompose-stack/radar-cp-hadoop-stack/travis
          ./setup-env.sh
          cd ../
          DOCKER_COMPOSE=${{ env.DOCKER_COMPOSE }} bin/radar-docker install
          sleep 120
          DOCKER_COMPOSE=${{ env.DOCKER_COMPOSE }} bin/radar-docker ps
          [ -z "$(DOCKER_COMPOSE=${{ env.DOCKER_COMPOSE }} bin/radar-docker ps | tail -n +3 | grep " Exit " | grep -v "kafka-init_1")" ]

      - name: Firebase messaging stack
        run: |
          cd  dcompose-stack/firebase-app-server
          cp etc/env.template .env
          sudo ${{ env.DOCKER_COMPOSE }} up -d --build && sleep 15 && [ -z "$(sudo ${{ env.DOCKER_COMPOSE }} ps | tail -n +3 | grep " Exit ")" ]
          sudo ${{ env.DOCKER_COMPOSE }} down

  # WIP: deploy to stage on merging into dev
  continuous-deployment:
    if: ${{ false }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [continuous-integration]

    # if: github.event_name == "push" && github.ref == "refs/heads/dev"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Create deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name radar-backend \
            --deployment-group-name RadarBackendDeploymentGroupName \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
